/*
 * lua_lib.h
 *
 * Reformated as a C string, otherwise verbatim
 *
 * @brief PICO-8 Wrapper for the TIC-80 Computer
 * https://github.com/musurca/pico2tic
 */

char p8totic_lua[] =
"--PICO-8 Wrapper for the TIC-80 Computer\n"
"--https://github.com/musurca/pico2tic\n"
"\n"
"--set palette\n"
"PAL_PICO8=\"0000001D2B537E2553008751AB52365F574FC2C3C7FFF1E8FF004DFFA300FFEC2700E43629ADFF83769CFF77A8FFCCAA\"\n"
"function PICO8_PALETTE()\n"
"	for i=0,15 do\n"
"		local r=tonumber(string.sub(PAL_PICO8,i*6+1,i*6+2),16)\n"
"		local g=tonumber(string.sub(PAL_PICO8,i*6+3,i*6+4),16)\n"
"		local b=tonumber(string.sub(PAL_PICO8,i*6+5,i*6+6),16)\n"
"		poke(0x3FC0+(i*3)+0,r)\n"
"		poke(0x3FC0+(i*3)+1,g)\n"
"		poke(0x3FC0+(i*3)+2,b)\n"
"	end	\n"
"end\n"
"\n"
"--sound\n"
"__sfx=sfx\n"
"function sfx(n,channel,offset)\n"
" --does not support offset as of 0.18.0\n"
"	if n<0 then\n"
"	 __sfx(0,28,channel,0)\n"
"	else\n"
"	 __sfx(0,28,channel)\n"
"	end\n"
"end\n"
"\n"
"function music(n,fadems,channelmask)\n"
" --do nothing as of 0.18.0\n"
"end\n"
"\n"
"--utility\n"
"function stat(i)\n"
" if i==0 then\n"
"	 return collectgarbage(\"count\")\n"
"	end\n"
" return 0.5\n"
"end\n"
"\n"
"--strings\n"
"function sub(str,i,j)\n"
" return str:sub(i,j)\n"
"end\n"
"\n"
"--permanent cart mem\n"
"function cartdata(id)\n"
" --do nothing\n"
"end\n"
"\n"
"function dget(i)\n"
" return pmem(i)\n"
"end\n"
"\n"
"function dset(i,val)\n"
" pmem(i,val)\n"
"end\n"
"\n"
"--tables\n"
"add=table.insert\n"
"\n"
"function all(list)\n"
"  local i = 0\n"
"  return function() i = i + 1; return list[i] end\n"
"end\n"
"\n"
"count=table.getn\n"
"\n"
"function del(t,a)\n"
"	for i,v in ipairs(t) do\n"
"		if v==a then\n"
"			t[i]=t[#t]\n"
"			t[#t]=nil\n"
"			return\n"
"		end\n"
"	end\n"
"end\n"
"\n"
"function foreach(t, f)\n"
"	for v in all(t) do\n"
"		f(v)\n"
"	end\n"
"end\n"
"\n"
"if mt ~= nil then\n"
"	mt = {}\n"
"end\n"
"\n"
"--math\n"
"srand=math.randomseed\n"
"sqrt=math.sqrt\n"
"abs=math.abs\n"
"min=math.min\n"
"max=math.max\n"
"flr=math.floor\n"
"pi=math.pi\n"
"\n"
"function rnd(a)\n"
" a=a or 1\n"
" return math.random()*a\n"
"end\n"
"\n"
"function sgn(a)\n"
" if a>=0 then return 1 end\n"
"	return -1\n"
"end\n"
"\n"
"function cos(a)\n"
" return math.cos(2*pi*a)\n"
"end\n"
"\n"
"function sin(a)\n"
" return -math.sin(2*pi*a)\n"
"end\n"
"\n"
"function atan2(a,b)\n"
" b=b or 1\n"
" return math.atan(a,b)/(2*pi)\n"
"end\n"
"\n"
"function mid(a,b,c)\n"
" if a<=b and a<=c then return max(a,min(b,c))\n"
"	elseif b<=a and b<=c then return max(b,min(a,c)) end\n"
"	return max(c,min(a,b))\n"
"end\n"
"\n"
"function band(a,b)\n"
" return flr(a)&flr(b)\n"
"end\n"
"\n"
"function bor(a,b)\n"
" return flr(a)|flr(b)\n"
"end\n"
"\n"
"function bxor(a,b)\n"
" return flr(a)^flr(b)\n"
"end\n"
"\n"
"function bnot(a,b)\n"
" return flr(a)~flr(b)\n"
"end\n"
"\n"
"function shl(a,b)\n"
" return a<<b\n"
"end\n"
"\n"
"function shr(a,b)\n"
" return a>>b\n"
"end\n"
"\n"
"--graphics\n"
"__p8_color=7\n"
"__p8_ctrans={true,false,false,false,false,false,false,false,\n"
"             false,false,false,false,false,false,false,false}\n"
"__p8_camera_x=0\n"
"__p8_camera_y=0\n"
"__p8_cursor_x=0\n"
"__p8_cursor_y=0\n"
"__p8_sflags={}\n"
"for i=1,256 do\n"
" __p8_sflags[i]=0\n"
"end\n"
"\n"
"function camera(cx,cy)\n"
" cx=cx or 0\n"
"	cy=cy or 0\n"
"	__p8_camera_x=-flr(cx)\n"
"	__p8_camera_y=-flr(cy)\n"
"end\n"
"\n"
"function cursor(cx,cy)\n"
" cx=cx or 0\n"
"	cy=cy or 0\n"
"	__p8_cursor_x=flr(cx)\n"
"	__p8_cursor_y=flr(cy)\n"
"end\n"
"\n"
"function __p8_coord(x,y)\n"
" return flr(x+__p8_camera_x),\n"
"	       flr(y+__p8_camera_y)\n"
"end\n"
"\n"
"__print=print\n"
"function print(str,x,y,c)\n"
" x=x or __p8_cursor_x\n"
"	y=y or __p8_cursor_y\n"
"	c=c or __p8_color\n"
"	c=peek4(0x7FE0+c)\n"
"	__print(str,x,y,c)\n"
"	__p8_cursor_y=y+8\n"
"end\n"
"\n"
"function color(c)\n"
" c=c or 7\n"
"	__p8_color=flr(c%16)\n"
"end\n"
"\n"
"function pal(c0,c1,type)\n"
" c0=c0 or -1\n"
"	c1=c1 or -1\n"
"	type=type or 0\n"
"	\n"
"	if c0<0 and c1<0 then\n"
"	 if type==0 then\n"
"		 for i=0,15 do\n"
"		  poke4(0x7FE0+i,i)\n"
"		 end\n"
"		else\n"
"		 PICO8_PALETTE()\n"
"		end\n"
"	else\n"
"	 c0=flr(c0%16)\n"
"	 if c1<0 then\n"
"		 c1=c0\n"
"		end\n"
"		c1=flr(c1%16)\n"
"		if type==0 then\n"
"		 poke4(0x7FE0+c0,c1)\n"
"	 else\n"
"		 local stri\n"
"			for i=0,5 do\n"
"			 stri=#__p8_pal-(c1+1)*6+i\n"
"			 poke4(0x3FC0*2+#__p8_pal-(c0+1)*6+i,tonumber(__p8_pal:sub(stri,stri),16))\n"
"			end\n"
"		end\n"
"	end\n"
"end\n"
"\n"
"function palt(c,trans)\n"
" c=c or -1\n"
"	if c<0 then -- reset\n"
"	 __p8_ctrans[1]=true\n"
"		for i=2,16 do\n"
"		 __p8_ctrans[i]=false\n"
"		end\n"
"	else\n"
"	 __p8_ctrans[flr(c%16)+1]=trans\n"
"	end\n"
"end\n"
"\n"
"function pset(x,y,c)\n"
" c=c or __p8_color\n"
"	c=peek4(0x7FE0+c)\n"
"	x,y=__p8_coord(x,y)\n"
" poke4(y*240+x,c) 	\n"
"end\n"
"\n"
"function pget(x,y)\n"
" x,y=__p8_coord(x,y)\n"
"	return peek4(y*240+x)\n"
"end\n"
"\n"
"__rect=rect\n"
"function rectfill(x0,y0,x1,y1,c)\n"
"	c=c or __p8_color\n"
"	c=peek4(0x7FE0+c)\n"
"	x0,y0=__p8_coord(x0,y0)\n"
"	x1,y1=__p8_coord(x1,y1)\n"
"	local w,h=x1-x0,y1-y0\n"
"	__rect(x0,y0,w+sgn(w),h+sgn(h),c)\n"
"end\n"
"\n"
"function rect(x0,y0,x1,y1,c)\n"
" c=c or __p8_color\n"
" c=peek4(0x7FE0+c)\n"
"	x0,y0=__p8_coord(x0,y0)\n"
"	x1,y1=__p8_coord(x1,y1)\n"
"	local w,h=x1-x0,y1-y0\n"
"	rectb(x0,y0,w+sgn(w),h+sgn(h),c) \n"
"end\n"
"\n"
"__circ=circ\n"
"function circfill(x,y,r,c)\n"
" c=c or __p8_color\n"
"	c=peek4(0x7FE0+c)\n"
"	x,y=__p8_coord(x,y)\n"
"	__circ(x,y,r,c)\n"
"end\n"
"\n"
"function circ(x,y,r,c)\n"
" c=c or __p8_color\n"
"	c=peek4(0x7FE0+c)\n"
"	x,y=__p8_coord(x,y)\n"
"	circb(x,y,r,c)\n"
"end\n"
"\n"
"__line=line\n"
"function line(x0,y0,x1,y1,c)\n"
" c=c or __p8_color\n"
" c=peek4(0x7FE0+c)\n"
"	x0,y0=__p8_coord(x0,y0)\n"
"	x1,y1=__p8_coord(x1,y1)\n"
" __line(x0,y0,x1,y1,c)\n"
"end\n"
"\n"
"function sspr(sx,sy,sw,sh,dx,dy,dw,dh) -- todo\n"
" dw=dw or sw\n"
"	dh=dh or sh\n"
" dx,dy=__p8_coord(dx,dy)\n"
"	if dx>240 or dy>136 then return end\n"
"	local xscale,yscale=dw/sw,dh/sh	\n"
"	local startx,starty,c=0,0\n"
" if dx<0 then startx=-dx end\n"
"	if dy<0 then starty=-dy end\n"
"	if dx+dw>240 then dw=240-dx end\n"
"	if dy+dh>136 then dh=136-dy end\n"
"	for x=startx,dw-1 do\n"
"	 for y=starty,dh-1 do\n"
"		 c=sget(sx+x/xscale,sy+y/yscale)\n"
"			c=peek4(0x7FE0+c)\n"
"			if not __p8_ctrans[c+1] then\n"
"		  poke4((dy+y)*240+dx+x,c)\n"
"			end\n"
"		end\n"
"	end\n"
"end\n"
"\n"
"__spr=spr\n"
"function spr(n,x,y,w,h) --todo flip_x,y\n"
" w=w or 1\n"
"	h=h or 1\n"
"	local sx,sy,xoff,yoff=n%16*8,flr(n/16)*8,0,0\n"
"	for j=0,h-1 do\n"
"	 for i=0,w-1 do\n"
"	  sspr(sx+xoff,sy+yoff,8,8,x+xoff,y+yoff)\n"
"			--__spr(n+j*16+i,x+i*8,y+j*8,__p8_ctrans)\n"
"		 xoff=xoff+8\n"
"		end\n"
"		yoff=yoff+8\n"
"		xoff=0\n"
"	end\n"
"end\n"
"\n"
"__map=map\n"
"function map(cel_x,cel_y,sx,sy,cel_w,cel_h)\n"
" sx,sy=__p8_coord(sx,sy)\n"
" local cel\n"
"	for cy=0,cel_h-1 do\n"
"	 for cx=0,cel_w-1 do\n"
"		 cel=mget(cx+cel_x,cy+cel_y)\n"
"			spr(cel,sx+cx*8,sy+cy*8)\n"
"		end\n"
"	end\n"
"	\n"
"	--__map(cel_x,cel_y,cel_w,cel_h,sx,sy,__p8_ctrans)\n"
"end\n"
"mapdraw=map\n"
"\n"
"function sset(x,y,c) \n"
" x,y=flr(x),flr(y)\n"
"	local addr=0x8000+64*(flr(x/8)+flr(y/8)*16)\n"
"	poke4(addr+(y%8)*8+x%8,c)\n"
"end\n"
"\n"
"function sget(x,y)\n"
" x,y=flr(x),flr(y)\n"
" local addr=0x8000+64*(flr(x/8)+flr(y/8)*16)\n"
"	return peek4(addr+(y%8)*8+x%8)\n"
"end\n"
"\n"
"function flip()\n"
" --do nothing\n"
"end\n"
"\n"
"--sprite flags\n"
"function fset(n,f,v)\n"
"	if f>7 then\n"
"	 __p8_sflags[n+1]=f\n"
"	else	 \n"
"	 local flags=__p8_sflags[n+1]\n"
"	 if v then\n"
"	  flags=flags|(1<<f)\n"
"		else\n"
"		 flags=flags&~(1<<f)\n"
"		end\n"
"	 __p8_sflags[n+1]=flags	\n"
"	end\n"
"end\n"
"\n"
"function fget(n,f)\n"
" f=f or -1\n"
"	if f<0 then\n"
"	 return __p8_sflags[n+1]\n"
"	end\n"
"	local flags=__p8_sflags[n+1]\n"
"	if flags&(1<<f)>0 then return true end\n"
"	return false\n"
"end\n"
"\n"
"--input\n"
"pico8ButtonMap = {}\n"
"pico8ButtonMap[1] = 2 -- 0 left\n"
"pico8ButtonMap[2] = 3 -- 1 right\n"
"pico8ButtonMap[3] = 0 -- 2 up\n"
"pico8ButtonMap[4] = 1 -- 3 down\n"
"pico8ButtonMap[5] = 4 -- 4 o\n"
"pico8ButtonMap[6] = 5 -- 5 x\n"
"pico8ButtonMap[7] = 6 -- 6 start\n"
"pico8ButtonMap[8] = 7 -- 7 Doesn\'t exist\n"
"function pico8ButtonToTic80(i, p)\n"
"	if p == nil then\n"
"		p = 0\n"
"	end\n"
"	return p * 8 + pico8ButtonMap[i + 1]\n"
"end\n"
"__btn = btn\n"
"function btn(i, p)\n"
"	return __btn(pico8ButtonToTic80(i, p))\n"
"end\n"
"__btnp = btnp\n"
"function btnp(i, p)\n"
"	return __btnp(pico8ButtonToTic80(i, p))\n"
"end\n"
"\n"
"-- TIC function to call pico-8 callbacks.\n"
"__updateTick = true\n"
"__initalized = false\n"
"function TIC()\n"
"	-- Initialize\n"
"	if __initalized == false then\n"
"		PICO8_PALETTE()\n"
"		if _init ~= nil then\n"
"			_init()\n"
"		end\n"
"		__initalized = true\n"
"	end\n"
"\n"
"	-- Update and Draw\n"
"	if _update60 ~= nil then -- 60 FPS\n"
"		_update60()\n"
"		if _draw ~= nil then _draw() end\n"
"	elseif _update ~= nil then -- 30 FPS\n"
"		if __updateTick then\n"
"			_update()\n"
"			if _draw ~= nil then _draw() end\n"
"		end\n"
"		__updateTick = not __updateTick\n"
"	end\n"
"end\n"
"\n"
"-- Add pico-8 cart below!\n";
